"""empty message

Revision ID: e7f598b01873
Revises: 
Create Date: 2019-11-15 15:26:00.793989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f598b01873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('estimated_time', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_description'), 'opportunity', ['description'], unique=False)
    op.create_index(op.f('ix_opportunity_estimated_time'), 'opportunity', ['estimated_time'], unique=False)
    op.create_index(op.f('ix_opportunity_fulfilled'), 'opportunity', ['fulfilled'], unique=False)
    op.create_index(op.f('ix_opportunity_location'), 'opportunity', ['location'], unique=False)
    op.create_index(op.f('ix_opportunity_timestamp'), 'opportunity', ['timestamp'], unique=False)
    op.create_index(op.f('ix_opportunity_type'), 'opportunity', ['type'], unique=False)
    op.create_table('volunteer_opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_opportunity')
    op.drop_index(op.f('ix_opportunity_type'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_timestamp'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_location'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_fulfilled'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_estimated_time'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_description'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_table('user')
    # ### end Alembic commands ###
