"""empty message

Revision ID: ee1893ddb318
Revises: 0b4543c610dc
Create Date: 2019-10-28 13:04:17.072335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1893ddb318'
down_revision = '0b4543c610dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('fulfilled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_opportunity_fulfilled'), 'opportunity', ['fulfilled'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_fulfilled'), table_name='opportunity')
    op.drop_column('opportunity', 'fulfilled')
    # ### end Alembic commands ###
